apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-o11y-server
spec:
  selector:
    matchLabels:
      app: argocd-o11y-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: argocd-o11y-server
    spec:
      containers:
        - env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: WAVEFRONT_ADDRESS
            value: https://intuit.wavefront.com/
          - name: WAVEFRONT_TOKEN
            value: ""
          image: sarabala1979/argo-o11y-server:v5
          imagePullPolicy: IfNotPresent
          name: argocd-o11y-server
          volumeMounts:
          - name: config-volume
            mountPath: /app/config.json
            subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: argocd-o11y-server-configmap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-o11y-server
  name: argocd-o11y-server
spec:
  ports:
    - name: metrics
      port: 9003
      targetPort: 9003
  selector:
    app: argocd-o11y-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-o11y-server-configmap
data:
  config.json: |
    {
      "prometheus": {
        "applications": [
          {
            "name": "default",
            "default": true,
            "dashboards": [
              {
                "groupKind": "pod",
                "rows": [
                  {
                    "name": "http",
                    "graphs": [
                      {
                        "name": "http_duration",
                        "title": "HTTP duration",
                        "description": "",
                        "graphType": "line",
                        "queryExpression": "sum(rate(container_cpu_usage_seconds_total{pod=~\"{{.name}}\", image!=\"\", container!=\"\", container_name!=\"POD\"}[5m])) by (container)"
                      }
                    ]
                  },
                  {
                    "name": "MEMORY",
                    "graphs": [
                      {
                        "name": "http_duration",
                        "title": "HTTP duration",
                        "graphType": "pie",
                        "duration": "1d",
                        "queryExpression": "rate(container_cpu_user_seconds_total [30s])*100"
                      },
                      {
                        "name": "http_duration",
                        "title": "HTTP duration",
                        "graphType": "pie",
                        "duration": "1d",
                        "queryExpression": "rate(container_cpu_user_seconds_total [30s])*100"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        "provider": {
          "Name": "default",
          "default": true,
          "address": "http://prometheus-service.monitoring.svc.cluster.local:8080"
        }
      }
    }
    
    
