apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-o11y-server
spec:
  selector:
    matchLabels:
      app: argocd-o11y-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: argocd-o11y-server
    spec:
      containers:
        - env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: WAVEFRONT_ADDRESS
            value: https://intuit.wavefront.com/
          - name: WAVEFRONT_TOKEN
            value: ""
          image: sarabala1979/argo-o11y-server:v14
          imagePullPolicy: IfNotPresent
          name: argocd-o11y-server
          ports:
           - containerPort: 9003
             name: metrics
             protocol: TCP
          resources:
           limits:
            cpu: 700m
            memory: 3Gi
           requests:
            cpu: 700m
            memory: 3Gi
          volumeMounts:
          - name: config-volume
            mountPath: /app/config.json
            subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: argocd-o11y-server-configmap
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-o11y-server
  name: argocd-o11y-server
spec:
  ports:
    - name: metrics
      port: 9003
      targetPort: 9003
  selector:
    app: argocd-o11y-server
